"""
Measured wire sizes, so documentation never quotes stale numbers.

  cosiechat sizes          Markdown table (SPEC.md embeds this output; a test checks it)

Every size is a whole packet as it goes on a road (no road auth), and
"LoRa frames" is how many RNode frames (508 bytes) it takes after fragmentation.
All inputs have fixed lengths, so the numbers are deterministic.
"""

from . import link as L
from . import message as M
from .identity import SUITES, Identity
from .packet import (
  ANNOUNCE,
  DATA,
  FRAGMENT_OVERHEAD,
  LINK_ACCEPT,
  LINK_DATA,
  LINK_REQUEST,
  RECEIPT,
  Packet,
  fragment,
)
from .ratchet import new_ratchet

LORA_MTU = 508
SEQUENCE = 1790000000000
TEXT = 'hello, how are you?'


def frames(packet: bytes, mtu: int = LORA_MTU) -> int:
  return 1 if len(packet) <= mtu else len(fragment(packet, mtu - FRAGMENT_OVERHEAD))


def measure(suite: str) -> dict:
  a, b = Identity.generate(suite), Identity.generate(suite)
  ra, rb = new_ratchet(a.kem_alg), new_ratchet(b.kem_alg)
  out = {'keyset': len(a.public_bytes)}

  def pkt(kind, payload, dest=a.address):
    return Packet(kind, 0, dest, None, payload).encode()

  args = dict(app_data={'name': 'alice'}, sequence=SEQUENCE)
  out['full announce'] = pkt(ANNOUNCE, M.make_announce(a, ra, full=True, **args))
  out['short announce'] = pkt(ANNOUNCE, M.make_announce(a, ra, full=False, **args))
  sealed, m = M.seal(
    a, [b.public()], TEXT, ratchets={b.address: rb.public()}, receipt_secret=b'\x00' * 16
  )
  out['message'] = pkt(DATA, sealed, b.address)
  out['receipt'] = pkt(RECEIPT, M.receipt_tag(m.receipt_secret, b.address) + b'\x00' * 8)
  pending = L.make_request(a, b.public(), rb.public())
  out['link request'] = pkt(LINK_REQUEST, pending.request, b.address)
  _, accept, kb = L.accept_request(
    b, pending.request, {a.address: a.public()}.get, ratchets=[rb], quantum_safe_only=False
  )
  out['link accept'] = pkt(LINK_ACCEPT, accept)
  body = L.message_body(TEXT, receipt_secret=b'\x00' * 16)
  out['link message'] = pkt(LINK_DATA, L.seal(kb, body))
  return out


def table() -> str:
  rows = {s: measure(s) for s in SUITES}
  kinds = list(next(iter(rows.values())))
  head = '| | ' + ' | '.join(f'`{s}`' for s in rows) + ' |'
  sep = '|---|' + '---:|' * len(rows)
  lines = [head, sep]
  for kind in kinds:
    cells = []
    for s in rows:
      v = rows[s][kind]
      if isinstance(v, bytes):
        n = frames(v)
        cells.append(f'{len(v):,} B' + (f' ({n} frames)' if n > 1 else ''))
      else:
        cells.append(f'{v:,} B')
    lines.append(f'| {kind} | ' + ' | '.join(cells) + ' |')
  lines.append('')
  lines.append(
    f'Whole packets without road auth; "frames" = RNode frames of {LORA_MTU} bytes after '
    f'fragmentation. Messages carry the {len(TEXT)}-character text "{TEXT}" and a receipt secret. '
    'Generated by `cosiechat sizes`.'
  )
  return '\n'.join(lines)


def main():
  print(table())


if __name__ == '__main__':
  main()
